services:
  dev:
    build: .
    volumes:
      - type: bind
        source: ../
        target: /workspace
      - type: bind
        source: ./setup
        target: /setup
        read_only: true
      - type: bind
        source: ./nvim
        target: /home/node/.config/nvim
        read_only: false
    command: /bin/bash -c "echo ready; tail -f /dev/null"
    ports:
      - 127.0.0.1:3000:3000
      - 127.0.0.1:4943:4943
